// Code generated by Slice Machine. DO NOT EDIT.

import RichText from './RichText/index.svelte';
import SliceExample from './SliceExample/index.svelte';

export const components = {
	rich_text: RichText,
	slice_example: SliceExample
};
